name: Deploy My Cloud Resume to S3

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="bucket_name=${{ secrets.BUCKET_NAME }}" -var="domain_name=${{ secrets.DOMAIN_NAME }}" -var="aws_region=${{ secrets.AWS_REGION }}" -var="tf_state_bucket=${{ secrets.TF_STATE_BUCKET }}" -var="tf_state_bucket_key=${{ secrets.TF_STATE_BUCKET_KEY }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var="bucket_name=${{ secrets.BUCKET_NAME }}" -var="domain_name=${{ secrets.DOMAIN_NAME }}" -var="aws_region=${{ secrets.AWS_REGION }}" -var="tf_state_bucket=${{ secrets.TF_STATE_BUCKET }}" -var="tf_state_bucket_key=${{ secrets.TF_STATE_BUCKET_KEY }}"
